base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Start home Page
    path('', views.home, name="home"),
    # END home Page

    # Start SSE
    path('WH2005M8D25H@L@', views.Data_notification, name='Data_notification'),
    path('H@L@m2l0ve1859Co/<str:pk>', views.Data_discussion, name='Data_discussion'),
    path('H@L@m2l0ve185', views.Data_home, name='Data_home'),
    # END SSE

    # Start Json Data
    path('Search/', views.Search, name="Search"),
    path('topic_list/', views.topic_list, name="topic_list"),
    path('Notification/', views.Notification, name='Notification'),
    path('topic/', views.topic, name='topic'),
    path('comments/<str:pk>', views.comments, name='comments'),
    path('CreateComment/<str:pk>', views.CreateComment, name='CreateComment'),
    path('CreateReact/<str:pk>', views.CreateReact, name='CreateReact'),
    path('ChackUsername', views.ChackUsername, name='ChackUsername'),
    path('ChackEmail', views.ChackEmail, name='ChackEmail'),
    # END Json Data

    # Start Ajax Page
    path('create-discussion/', views.createDiscussion, name="create-discussion"),
    path('Edit-Discussion/<str:pk>', views.updateDiscussion, name="update-discussion"),
    path('delete-discussion/<str:pk>', views.deleteDiscussion, name="delete-discussion"),
    path('delete-Commints/<str:pk>', views.deleteCommints, name="delete-Commints"),
    path('Followers', views.Followers, name="Followers"),
    path('ChangePassword', views.ChangePassword, name="ChangePassword"),
    # END Ajax Page

    # Start Page 
    path('login/', views.LoginPage, name="login"),
    path('register/', views.RegisterPage, name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('profile/<str:pk>', views.Profile, name="profile"),
    path('Settings/<str:pk>', views.Settings, name="Settings"),
    path('discussion/<str:pk>/', views.discussion, name="discussion"),
    # END Page 
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.core.validators import RegexValidator


class User(AbstractUser):
    GENDER_CHOICES = [('M', 'Male'),('F', 'Female')]
    username_validator = RegexValidator(regex=r'^[A-Za-z0-9-]{3,}$', message='The Username must contain only lowercase letters and English numbers and you can use: "-". It must be at least 3 characters long.',)
    username = models.CharField(max_length=30, unique=True, validators=[username_validator],)
    first_name = models.CharField(max_length=15, null=True, blank=False)
    last_name = models.CharField(max_length=15, null=True, blank=False)
    email = models.EmailField(unique=True, null=True, blank=False)
    bio = models.TextField(max_length=255, blank=False,default="Hello, World")
    portfolio = models.TextField(blank=False,max_length=5000 ,null=True, default="# Hello, World")
    display_notification = models.BooleanField(default=True)
    github = models.CharField(max_length=100,blank=True,null=False)
    followers = models.ManyToManyField('self', symmetrical=False, related_name='following', blank=True)
    birth_date = models.DateField(null=True, blank=True)
    Use_code  = models.CharField(max_length=50, null=True, blank=True)
    Job = models.CharField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    CodeCoin = models.IntegerField(default=0)
    avatar = models.ImageField(null=True, default="avatar.svg")
    smallavatar = models.ImageField(null=True, default="avatar.svg")
    


    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []
    
    @property
    def rank(self):
        rank = Rank.objects.filter(user=self).first()
        if rank:
            return rank
        return None


class Topic(models.Model):
    name = models.CharField(max_length=20)


    def __str__(self):
        return self.name


class Discussion(models.Model):
    name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True) 
    topic = models.ForeignKey(Topic,max_length=20, on_delete=models.CASCADE, null=True)
    use_commints = models.BooleanField(default=True)
    Viewss = models.ManyToManyField(User,related_name='Viewss', blank=True)
    Likes = models.ManyToManyField(User, related_name='liked_posts', related_query_name='liked_post', blank=True)
    disLikes = models.ManyToManyField(User, related_name='disliked_posts', related_query_name='disliked_post', blank=True)
    title = models.CharField(max_length=100,blank=False)
    content = models.TextField(max_length=5000, blank=False, null=True )
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    @property
    def rank(self):
        rank = Rank.objects.filter(user=self.name).first()
        if rank:
            return rank.rank
        return None


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
    body = models.TextField(max_length=1000,blank=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.body[0:50]


class Rank(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ranks')
    respect = models.IntegerField(default=0)
    rank = models.CharField(max_length=50, blank=True, null=True)
    Logo_rank = models.ImageField(null=True, default="Rank/BronzeIII.svg")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering = ['-respect']

    from .RankList import update_rank
    

@receiver(post_save, sender='auth.User')
def update_user_rank(sender, instance, created, **kwargs):
    if created:
        rank = Rank(user=instance)
    else:
        rank = instance.ranks.first()
    rank.respect = instance.profile.respect
    rank.update_rank()
    rank.save()
    
    

@receiver(post_save, sender=User)
def create_user_rank(sender, instance, created, **kwargs):
    if created:
        rank = Rank(user=instance, respect=0)
        rank.update_rank()
        rank.save()
        instance.ranks.add(rank)
        

class Rank_history(models.Model):
    TYPE_RANK = [('Loss','Loss'),('Add','Add')]
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255,null=True, blank=False)
    OldRank = models.IntegerField(blank=False)
    NewRank = models.IntegerField(blank=False)
    points = models.IntegerField(blank=False)
    type = models.CharField(max_length=4,choices=TYPE_RANK, null=True, blank=False)
    read = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    
    
class CodeCoin_history(models.Model):
    TYPE_RANK = [('Loss','Loss'),('Add','Add')]
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255,null=True, blank=False)
    CodeCoinOld = models.IntegerField(blank=False)
    CodeCoinNew = models.IntegerField(blank=False)
    points = models.IntegerField(blank=False)
    type = models.CharField(max_length=4,choices=TYPE_RANK, null=True, blank=False)
    read = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created']



class notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=255,blank=False)
    url = models.CharField(max_length=100,blank=False)
    read = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created']

base/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Discussion,User
from django.core.exceptions import ValidationError
from datetime import date


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email','birth_date', 'password1', 'password2']
        widgets = {
            'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        birth_date = cleaned_data.get('birth_date')
        if birth_date:
            age = (date.today() - birth_date).days // 365
            if age < 18:
                raise ValidationError("Age must be 18 years or older.")

        


class DiscussionForm(ModelForm):
    class Meta:
        model = Discussion 
        fields = ['title', 'content']

        
class EditUser(ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','github','bio','birth_date','location','gender','Use_code','display_notification']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-Settings'}),
            'last_name': forms.TextInput(attrs={'class': 'form-Settings'}),
            'bio': forms.Textarea(attrs={'class': 'form-Settings bio-Settings '}),
            'birth_date': forms.DateInput(attrs={'class': 'form-Settings', 'type': 'date'}),
            'location': forms.TextInput(attrs={'class': 'form-Settings'}),
            'gender': forms.Select(attrs={'class': 'form-Settings'}),
            'display_notification': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'github': forms.TextInput(attrs={'class': 'form-Settings'}),
            'Use_code': forms.TextInput(attrs={'class': 'form-Settings'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        birth_date = cleaned_data.get('birth_date')
        if birth_date:
            age = (date.today() - birth_date).days // 365
            if age < 18:
                raise ValidationError("Age must be 18 years or older.", code='invalid', params={})

class EditPortfolio(ModelForm):
    class Meta:
        model = User
        fields = ['portfolio']
        widgets = {
            'portfolio': forms.Textarea(attrs={'class': 'portfolio'}),
        }

base/templates/base/Settings.html
{% extends 'main.html' %}

{% block title %} Settings {{user.username}} {% endblock title %}

{% block content %}

<div class="Your_Profile">
    <div class="flex">
        <div class="Your_Profile_img">
            <img src="{{user.avatar.url}}" alt="{{user.username}}">
        </div>
        <div class="Your_Profile_Data">
            <a href="/profile/{{user.username}}">
                <h3> {{user.first_name}} {{user.last_name}} <small>({{user.username}})</small> </h3>
            </a>
            <p>Your personal account</p>
        </div>
    </div>
</div>

<div class="Settings_container">

    <div class="Settings_Lest">
        <div class="Settings_Lest_account">
            <small><p>Profile</p></small>
            <ul>
                <div id="Profile">
                    <li>
                        <a href="/Settings/Profile">
                            <div>    
                                <span> {% include 'icon/user.svg' %} Public Profile</span>
                            </div>
                        </a>
                    </li>
                </div>
                    
                <div id="admin">
                    <li>
                        <a href="/Settings/admin">
                            <div>
                                <span> {% include 'icon/settings.svg' %} Account </span>
                            </div>
                        </a>
                    </li>
                </div>

                <div id="Portfolio">
                    <li>
                        <a href="/Settings/Portfolio">
                            <div>
                                <span> {% include 'icon/document.svg' %}  Portfolio </span>
                            </div>
                        </a>
                    </li>
                </div>
            </ul>

        </div>
    </div>
    
    <script>
            let element = document.getElementById("{{pk}}");
            element.classList.add("active_Settings");
    </script>
    
    <div>
        {% if pk == 'Profile' %}
            <div class="Settings_Profile">
                <div class="Profile_group">

                    <div class="Settings_Profile_Edit_Img">
                        <img id="outputImage" src="{{user.avatar.url}}" alt="{{user.username}}">
                        <a id="Edit-Img" class="Edit-Img border-hr"> {% include 'icon/edit.svg' %} Edit</a>
                    </div>

  
        <div class="Form_Profile">
            {% if messages %}
            <div class="status_message">
                {% for massage in messages %}
                {% if status == True %}
                <div class="alert alert-success">
                    <strong>Success!</strong> {{massage}}
                </div>
                {% else %}
                <div class="errorlist">
                    <strong>Error!</strong> {{massage}} {{ error }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}  
            
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_EditUser }}
                <input class="display-none" type="file" id="avatar" name="avatar" accept=".jpg, .jpeg, .png">
                <p>
                    Notifications do not appear on mobile phones
                </p>
                <hr>
                <input id="Btn_Submit_Discussion" class="btn btn-primary" type="submit" value="Save"/>
            </form>
        </div>

        </div>
    </div>
                
            <script>
            const Edit_Img = document.querySelector('#Edit-Img');
            const avatar = document.getElementById('avatar');
            const outputImage = document.getElementById('outputImage');

            Edit_Img.addEventListener("click", event => {
                avatar.click();
            });

            avatar.addEventListener('change', function() {
                const file = this.files[0];
                const reader = new FileReader();

            reader.addEventListener('load', function() {
                outputImage.src = this.result;
            });

                reader.readAsDataURL(file);
            });

    document.addEventListener('keydown', function(event) {
        if (event.ctrlKey && event.key.toLowerCase() === 's') {
            event.preventDefault();
            Btn_Submit_Discussion.click();
        }
    });

</script>


        {% elif pk == 'admin' %}
        <div class="EditAccount">
            <h1>This page is not completed in the trial version</h1>
            <div>
                <a href="#">Change Password</a>
            </div>
            <div>
                <a href="#">Change Username</a>
            </div>
            <div>
                <a href="#">Change Email</a>
            </div>
            
        </div>
        
        {% elif pk == 'Portfolio' %}

        <div class="Portfolio-container">
            <form action="" method="post">
                {% csrf_token %}
                <div class="TitlePortfolio flex">
                    <div class="title">
                        Portfolio
                    </div>
                    <div class="margin-auto ">
                        <input id="Btn_Submit_Discussion" class="btn btn-primary" type="submit" value="Save"/>
                        <a class="btn btn-danger Close" href="/profile/{{request.user.username}}">Close</a>
                    </div>
                </div>
                <div class="EditPortfolio">
                    <div id="text-editor" class="editor markdown-textarea">
                        <div class="line-numbers">
                            <div></div>
                        </div>
                        {{form_EditPortfolio.portfolio}}
                    </div>
                </div>
            </form>
        </div>


<script>

    document.addEventListener('DOMContentLoaded', event => {
        const textarea = document.querySelector('#id_portfolio')
        const lineNumbers = document.querySelector('.line-numbers')
        const numberOfLines = textarea.value.split('\n').length
        
        lineNumbers.innerHTML = Array(numberOfLines)
            .fill('<div></div>')
            .join('')
    
        textarea.addEventListener('keyup', event => {
            const numberOfLines = event.target.value.split('\n').length
            lineNumbers.innerHTML = Array(numberOfLines)
            .fill('<div></div>')
            .join('')
        });
    
        textarea.addEventListener('keydown', event => {
          if (event.key === 'Tab') {
            event.preventDefault();
            const start = textarea.selectionStart;
            const end = textarea.selectionEnd;
            const oldValue = textarea.value;
            textarea.value = oldValue.substring(0, start) + '\t' + oldValue.substring(end);
            textarea.setSelectionRange(start + 1, start + 1);
          }
      });
    });
    
    </script>
  
<script>
        document.addEventListener('keydown', function(event) {
        if (event.ctrlKey && event.key.toLowerCase() === 's') {
        event.preventDefault();
        Btn_Submit_Discussion.click();
    }
});
    </script>

        {% endif %}


    </div>

</div>


{% endblock content %}

base/templates/base/TopDiscussion.html
{% load custom_filters %}
{% if discussion_count == 0 %}

<div class="TopDiscussion">
    <div class="Top-Title">
        <h5>Top Three Discussions</h5>
    </div>

    <div class="TopDiscussion_None border-hr">
            There are No Discussions    
    </div>
</div>

{% else %}
<div class="TopDiscussion">
    <div class="Top-Title">
        <h5>Top Three Discussions</h5>
    </div>
    {% for Discussion in TopDiscussion %}
    <div class="TopDiscussion_Data border-hr effect_text_top animation-1s">
        <div class="TopDiscussion_User flex">
            <div class="TopDiscussion_img">
                <img src="{{ Discussion.name.smallavatar.url }}" alt="">
            </div>
            <div>
                    <a href="profile/{{Discussion.name.username}}">
                    <small>{{ Discussion.name.name }}</small>
                </a>
                <p>
                    <small>{{ Discussion.name.rank.rank }}</small>
                </p>
                </div>
        </div>

        <div class="TopDiscussion_Title">
            <a href="discussion/{{Discussion.id}}">
                <small>
                    {{ Discussion.title }}
                </small>
            </a>
        </div>
        <div class="flex">
            <div class="TopDiscussion_Topic">
                <a href="/?topic={{ Discussion.topic }}">
                    <small>
                        {{ Discussion.topic }}
                    </small>
                </a>
            </div>

            <div class="margin-auto TopDiscussion_Comments">
                <div class="flex">
                    <div class="TopDiscussion_icon">
                        {% include 'icon/comments.svg' %}
                    </div>
                    <div>
                        <small>
                            {{ Discussion.CountComments|shorten_number }}
                        </small>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
        {% endfor %}
</div>
{% endif %}

base/templates/base/TopRank.html
{% load custom_filters %}
<div>
    <h5>Top Three Ranks</h5>
</div>
<div class="Top_Rank">
    {% for Ranks in TopRank %}
        <div class="effect_text_top animation-1s TopRank_List border-hr">
            <div class="flex">
                <div class="img_TopRank">
                    <img src="{{ Ranks.user.smallavatar.url }}" alt="">
                </div>
                <div class="Data_TopRank">
                    <a href="profile/{{ Ranks.user.username }}">
                        <p>{{ Ranks.user.name }}</p></a>
                        <small>{{ Ranks.rank }}</small>
                        <small>{{ Ranks.respect|shorten_number }}</small>
                </div>
            </div>
        </div>
        {% endfor %}
</div>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

<form method="post" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"</p>
    <a href="{{request.META.HTTP_REFERER}}">Back</a>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

base/templates/base/discussion_form.html
{% extends 'main.html' %}
{% block title %} Edit Discussion {% endblock %}
{% block content %}


<div class="discussion-form-container">

<div class="form-container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="input-title-container input-container">
            <div class="input-Topic">
                <label>Topic</label>
                <div class="error-Topic effect_text_top animation-1s"><small>You must enter three or more characters</small></div>
                    <input maxlength="20" id="id_topic" type="text" autocomplete="off" value="{{ discussion.topic.name }}" name="topic" list="topic-list">
                <div class="Topics_Results_continar">
                    <ul id="Topics-Search-Results">
                      
                    </ul>
                  </div>
        </div>
        
        <div class="input-Discussion-title">
            <label>Title</label>
            <div class="error-Title effect_text_top animation-1s"><small>You must enter 10 or more characters</small></div>
            {{ form.title }}
            </div>
        </div>

        <label class="label-Discussion-Content">Content</label>
        <div class="error-editor effect_text_top animation-1s"><small>You must enter 50 or more characters</small></div>
        
            <div class="editor markdown-textarea">
                    <div class="line-numbers">
                        <div></div>
                    </div>
                    {{ form.content }}
                </div>
        <br>
        <div class="Submit-Discussion">
            <div class="flex">
                <div>
                    <a class="btn btn-danger" href="{{request.META.HTTP_REFERER}}">Back</a>
                </div>

                <div class="margin-auto">
                    <input id="Btn_Submit_Discussion" class="btn btn-primary" type="Submit" value="Submit" \>
                </div>

            </div>
        </div>
    </form>
    </div>
</div>


<div>
    
</div>

<script>
    const id_topic = document.getElementById('id_topic');
    const id_title = document.getElementById('id_title');
    const id_content = document.getElementById('id_content');
    const Btn_Submit_Discussion = document.getElementById('Btn_Submit_Discussion');
    const text_editor = document.querySelector('.editor');
    let error_Topic = document.querySelector('.error-Topic');
    let error_Title = document.querySelector('.error-Title');
    let error_editor = document.querySelector('.error-editor');
    

    document.addEventListener('click', function(event) {
    const element_event = event.target;
    if (element_event.id === 'Btn-Create-Discussions'){
      Open_Create = true;
      id_topic.focus();
    }
    if (element_event.id === 'Close-Submit'){
      Open_Create = false;
    }

  });
  document.addEventListener('keydown', function(event) {
  if (event.ctrlKey && event.key.toLowerCase() === 's') {
    event.preventDefault();
      Btn_Submit_Discussion.click();
  }
});



id_topic.addEventListener('blur', function(event) {
  if (id_topic.value.length  <= 2 || id_topic.value.length  >= 21){
    id_topic.style.border = "1px var(--Error_color) solid";
    error_Topic.style.display = "block";
  }});
  
  id_title.addEventListener('blur', function(event) {
    if (id_title.value.length < 10){
      id_title.style.border = "1px var(--Error_color) solid";
      error_Title.style.display = "block";
    }
  });
  id_content.addEventListener('blur', function(event) {
    if (id_content.value.length < 50){
      text_editor.style.border = "1px var(--Error_color) solid";    
      error_editor.style.display = "block";
    }
  });
  
    function check_Data_discussion(){
    if ( id_topic.value.length > 2 && id_title.value.length > 10 && id_content.value.length > 50 ){
      Btn_Submit_Discussion.removeAttribute('disabled');
    }
    if (id_content.value.length < 50 ||  id_content.value.length > 20000 || id_title.value.length < 10  || id_title.value.length > 100|| id_topic.value.length  < 2 || id_topic.value.length  > 20 ){
      Btn_Submit_Discussion.setAttribute('disabled','');
    }

    if (id_topic.value.length > 2){ 
      id_topic.style.border = "1px var(--hr_color) solid";
      error_Topic.classList.remove("effect_text_top");
      error_Topic.classList.add("effect_hide_text_top");
      setTimeout(()=> {
        error_Topic.style.display = 'none';
        error_Topic.classList.remove("effect_hide_text_top");
        error_Topic.classList.add("effect_text_top");
      },900)
    }
    if (id_title.value.length > 10){
      id_title.style.border = "1px var(--hr_color) solid";
      error_Title.classList.remove("effect_text_top");
      error_Title.classList.add("effect_hide_text_top");
      setTimeout(()=> {
        error_Title.style.display = 'none';
        error_Title.classList.remove("effect_hide_text_top");
        error_Title.classList.add("effect_text_top");
      },900)
    }
    if (id_content.value.length > 50){ 
      text_editor.style.border = "1px var(--hr_color) solid";
      error_editor.classList.remove("effect_text_top");
      error_editor.classList.add("effect_hide_text_top");
      setTimeout(()=> {
        error_editor.style.display = 'none';
        error_editor.classList.remove("effect_hide_text_top");
        error_editor.classList.add("effect_text_top");
      },900)
    }
    };

    document.addEventListener('click', function(event) {check_Data_discussion();});
    document.addEventListener('input', function(event) {check_Data_discussion();});

    
</script>


<script>
document.addEventListener('DOMContentLoaded', event => {
    const textarea = document.querySelector('textarea')
    const lineNumbers = document.querySelector('.line-numbers')
    const numberOfLines = textarea.value.split('\n').length
    
    lineNumbers.innerHTML = Array(numberOfLines)
        .fill('<div></div>')
        .join('')

    textarea.addEventListener('keyup', event => {
        const numberOfLines = event.target.value.split('\n').length
        lineNumbers.innerHTML = Array(numberOfLines)
        .fill('<div></div>')
        .join('')
    })

    textarea.addEventListener('keydown', event => {
          if (event.key === 'Tab') {
            event.preventDefault();
            const start = textarea.selectionStart;
            const end = textarea.selectionEnd;
            const oldValue = textarea.value;
            textarea.value = oldValue.substring(0, start) + '\t' + oldValue.substring(end);
            textarea.setSelectionRange(start + 1, start + 1);
          }
      });
})
</script>


<script>
    const Input_Topics = document.querySelector('#id_topic');
    const TopicList = document.querySelector('#Topics-Search-Results');
  
  Input_Topics.addEventListener('input', function(event) {
        let HTML = '';
        TopicList.style.display="none";
        if(Input_Topics.value){
          $.ajax({
              url:"{% url 'topic_list' %}",
              data:{'input':Input_Topics.value},
              success:function(data){
                for(Data_topic of data.topics ){
                  HTML += `<li ><div class="Data_topic">${Data_topic.name}</div></li>`
                }
                TopicList.innerHTML = HTML;
                TopicList.style.display="block";
              }
              
            });
          }
      });
    Input_Topics.addEventListener("focus", function() { 
          TopicList.style.display="block";
      });
    Input_Topics.addEventListener("blur", function() {
          setTimeout(function() {
      TopicList.style.display="none";
  }, 200); 
  });
  
  $(document).on("click", ".Data_topic", function(){
    var selectedTopic = $(this).text(); 
    $("#id_topic").val(selectedTopic);
  });
  
  </script>

{% endblock content %}